# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marco Romero
author: Marco Antonio Romero
email: marcoromero_1@hotmail.com
tagline: Desarrollador Web Full Stack y Docente
description: >- # this means to ignore newlines until "baseurl:"
  Desarrollador Web Full Stack, con HTML5 CSS JavaScript Python y Django - FrontEnd y BackEnd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcoromero.com.ar" # the base hostname & protocol for your site, e.g. http://example.com
locale: es_AR
lang: es
twitter_username: darkfoe703
github_username: darkfoe703

google_analytics: UA-61071534-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

logo: /assets/images/perfil00.jpg

image:
  path: /assets/images/perfil00.jpg
  height: 256
  width: 256

social:
  name: Marco Romero
  links:
    - https://twitter.com/Darkfoe703
    - https://www.instagram.com/darkfoe703
    - https://www.linkedin.com/in/marco-romero-at/
    - https://github.com/darkfoe703

logo: /assets/images/perfil00.jpg

image:
  path: /assets/images/perfil00.jpg
  height: 256
  width: 256

social:
  name: Marco Romero
  links:
    - https://twitter.com/Darkfoe703
    - https://www.instagram.com/darkfoe703
    - https://www.linkedin.com/in/marco-romero-at/
    - https://github.com/darkfoe703
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

page_excerpts: true
