# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marco Romero
author: Marco Antonio Romero
email: marcoromero.dev@gmail.com
tagline: Backend Developer and Teacher
description: >- # this means to ignore newlines until "baseurl:"
  Backend Developer, with Python, Django, Flask, PostgreSQL, Docker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcoromero.com.ar" # the base hostname & protocol for your site, e.g. http://example.com
# Localization
locale: en_US
lang: en
# Multilingual
languages: ["en", "es"]
# Social users
twitter_username: darkfoe703
github_username: darkfoe703
# Google Analytics code
google_analytics: G-GLZGEY040K

# skills:
#   - python
#   - flask
#   - django
#   - postgresql
#   - docker
#   - linux
#   - API
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

logo: /assets/images/perfil01.webp

image:
  path: /assets/images/perfil01.webp
  height: 256
  width: 256

# Social links
social:
  name: Marco Romero
  links:
    - https://www.instagram.com/darkfoe703
    - https://www.linkedin.com/in/marco-romero-at/
    - https://github.com/darkfoe703
    - https://t.me/Darkfoe703

include:
  - es
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - es/README_es.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

page_excerpts: true

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false